M48
; DRILL file {KiCad (6.0.8-1)-1} date Wednesday, November 30, 2022 at 09:42:05 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-30T21:42:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0350
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0374
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
%
G90
G05
T1
X4.3543Y-2.0551
T2
X3.8257Y-2.6834
X3.9208Y-2.7143
X4.016Y-2.7452
T3
X3.8403Y-1.9084
X3.934Y-1.878
X4.0276Y-1.8476
T4
X4.3988Y-1.9912
X4.4567Y-2.0709
T0
M30
